/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"
/* Header for class com_example_javie_practicarecuperacion_faceDetection */

using namespace cv;
#ifndef _Included_com_example_javie_practicarecuperacion_faceDetection
#define _Included_com_example_javie_practicarecuperacion_faceDetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_javie_practicarecuperacion_faceDetection
 * Method:    faceDetection
 * Signature: (J)V
 */
 void detect(Mat& frame);
JNIEXPORT void JNICALL Java_com_example_javie_practicarecuperacion_faceDetection_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
